containers:
      - name: order-service
        image: 190771706930.dkr.ecr.eu-west-3.amazonaws.com/atlasflow-order-service:latest
        
        # --- DÉBUT SECURITYCONTEXT ---
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        # --- FIN SECURITYCONTEXT ---
        
        ports:
        - containerPort: 8000