resources:
  - inventory/deployment.yaml
  - inventory/service.yaml
  - notification/deployment.yaml
  - notification/service.yaml
  - order/deployment.yaml
  - order/service.yaml
  #- kafka/kafka.yaml
  #- postgres/postgres.yaml